# wics_major.json

In [2]:
import json 
import pandas as pd

In [3]:
with open('./row/wics_major.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

In [4]:
data.keys()

dict_keys(['description', 'source', 'items'])

In [20]:
df = pd.json_normalize(data, record_path=['items'], meta=['description'])
df.head()

  code     name              description
0   10      에너지  WICS 대분류 (Major Sector)
1   15       소재  WICS 대분류 (Major Sector)
2   20      산업재  WICS 대분류 (Major Sector)
3   25  경기관련소비재  WICS 대분류 (Major Sector)
4   30    필수소비재  WICS 대분류 (Major Sector)

In [21]:
df.rename(columns={
        'code': 'wics_major_code', 'name': 'wics_major_name', 'description': 'wics_major_description'
    }, 
    inplace=True)
df.head()

  wics_major_code wics_major_name   wics_major_description
0              10             에너지  WICS 대분류 (Major Sector)
1              15              소재  WICS 대분류 (Major Sector)
2              20             산업재  WICS 대분류 (Major Sector)
3              25         경기관련소비재  WICS 대분류 (Major Sector)
4              30           필수소비재  WICS 대분류 (Major Sector)

In [22]:
df.shape

(10, 3)

# wics_medium.json

In [ ]:
with open('./row/wics_medium.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

In [24]:
df_medium = pd.json_normalize(data, record_path=['items'], meta=['description'])
df_medium.head()

   code       name major_code                                description
0  1010        에너지         10  WICS 중분류 (Medium Sector / Industry Group)
1  1510         소재         15  WICS 중분류 (Medium Sector / Industry Group)
2  2010        자본재         20  WICS 중분류 (Medium Sector / Industry Group)
3  2020  상업서비스와공급품         20  WICS 중분류 (Medium Sector / Industry Group)
4  2030         운송         20  WICS 중분류 (Medium Sector / Industry Group)

In [25]:
df_medium.rename(columns={
    'code': 'wics_medium_code', 'name': 'wics_medium_name', 'description': 'wics_medium_description',
    'major_code': 'wics_major_code'
    }, 
    inplace=True)
df_medium.head()

,wics_medium_code,wics_medium_name,wics_major_code,wics_medium_description
0,1010,에너지,10,WICS 중분류 (Medium Sector / Industry Group)
1,1510,소재,15,WICS 중분류 (Medium Sector / Industry Group)
2,2010,자본재,20,WICS 중분류 (Medium Sector / Industry Group)
3,2020,상업서비스와공급품,20,WICS 중분류 (Medium Sector / Industry Group)
4,2030,운송,20,WICS 중분류 (Medium Sector / Industry Group)

In [26]:
df_medium.shape

(28, 4)

## merge

In [27]:
df = df.merge(df_medium, on='wics_major_code', how='left')
df.head()

,wics_major_code,wics_major_name,wics_major_description,wics_medium_code,wics_medium_name,wics_medium_description
0,10,에너지,WICS 대분류 (Major Sector),1010,에너지,WICS 중분류 (Medium Sector / Industry Group)
1,15,소재,WICS 대분류 (Major Sector),1510,소재,WICS 중분류 (Medium Sector / Industry Group)
2,20,산업재,WICS 대분류 (Major Sector),2010,자본재,WICS 중분류 (Medium Sector / Industry Group)
3,20,산업재,WICS 대분류 (Major Sector),2020,상업서비스와공급품,WICS 중분류 (Medium Sector / Industry Group)
4,20,산업재,WICS 대분류 (Major Sector),2030,운송,WICS 중분류 (Medium Sector / Industry Group)

# wics_minor.json

In [ ]:
with open('./row/wics_minor.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

df_minor = pd.json_normalize(data, record_path=['items'], meta=['description'])

df_minor.rename(columns={
    'code': 'wics_minor_code', 'name': 'wics_minor_name', 'description': 'wics_minor_description',
    'medium_code': 'wics_medium_code'
    }, 
    inplace=True)
df_minor.head()

,wics_minor_code,wics_minor_name,wics_medium_code,wics_minor_description
0,101010,에너지장비및서비스,1010,WICS 소분류 (Minor Sector / Industry)
1,101020,석유와가스,1010,WICS 소분류 (Minor Sector / Industry)
2,151010,화학,1510,WICS 소분류 (Minor Sector / Industry)
3,151030,포장재,1510,WICS 소분류 (Minor Sector / Industry)
4,151040,비철금속,1510,WICS 소분류 (Minor Sector / Industry)

In [29]:
df_minor.shape

(79, 4)

## merge

In [30]:
df = df.merge(df_minor, on='wics_medium_code', how='left')
df.head()

,wics_major_code,wics_major_name,wics_major_description,wics_medium_code,wics_medium_name,wics_medium_description,wics_minor_code,wics_minor_name,wics_minor_description
0,10,에너지,WICS 대분류 (Major Sector),1010,에너지,WICS 중분류 (Medium Sector / Industry Group),101010,에너지장비및서비스,WICS 소분류 (Minor Sector / Industry)
1,10,에너지,WICS 대분류 (Major Sector),1010,에너지,WICS 중분류 (Medium Sector / Industry Group),101020,석유와가스,WICS 소분류 (Minor Sector / Industry)
2,15,소재,WICS 대분류 (Major Sector),1510,소재,WICS 중분류 (Medium Sector / Industry Group),151010,화학,WICS 소분류 (Minor Sector / Industry)
3,15,소재,WICS 대분류 (Major Sector),1510,소재,WICS 중분류 (Medium Sector / Industry Group),151030,포장재,WICS 소분류 (Minor Sector / Industry)
4,15,소재,WICS 대분류 (Major Sector),1510,소재,WICS 중분류 (Medium Sector / Industry Group),151040,비철금속,WICS 소분류 (Minor Sector / Industry)

In [31]:
df.shape

(79, 9)

# wics_detailed.json

In [ ]:
with open('./row/wics_detailed.json', 'r', encoding='utf-8') as f:
    data = json.load(f)
df_detailed = pd.json_normalize(data, record_path=['items'])

df_detailed.rename(columns={
    'code': 'wics_detailed_code', 'name': 'wics_detailed_name', 'description': 'wics_detailed_description',
    'minor_code': 'wics_minor_code'
    }, 
    inplace=True)

df_detailed.head()

,wics_detailed_code,wics_detailed_name,wics_minor_code,wics_detailed_description
0,10101010,석유와 가스 등 시추,101010,유정 시추를 위해 서비스 계약을 체결한 시추 계약업자 또는 시추 장치 소유자. 태양...
1,10101020,석유와 가스 등 에너지 장비 및 서비스,101010,"시추 장치 및 장비를 제조하는 업체, 그리고 석유와 가스 유정의 시추, 평가, 생산..."
2,10102010,종합 석유 및 가스,101020,"석유와 가스의 탐사 및 생산과 관련된 종합 석유 회사로서, 이 외에 정유, 마케팅,..."
3,10102020,석유와 가스 탐사 및 생산,101020,다른 부문으로 분류되지 않은 석유와 가스의 탐사 및 생산 관련 기업
4,10102030,석유와 가스 정제 및 마케팅,101020,'종합 석유 및 가스' 또는 '독립 전력 생산업체 및 에너지 거래업체' 로 분류되지...

In [34]:
df_detailed.shape

(151, 4)

## merge

In [35]:
df = df.merge(df_detailed, on='wics_minor_code', how='left')
df.head()

,wics_major_code,wics_major_name,wics_major_description,wics_medium_code,wics_medium_name,wics_medium_description,wics_minor_code,wics_minor_name,wics_minor_description,wics_detailed_code,wics_detailed_name,wics_detailed_description
0,10,에너지,WICS 대분류 (Major Sector),1010,에너지,WICS 중분류 (Medium Sector / Industry Group),101010,에너지장비및서비스,WICS 소분류 (Minor Sector / Industry),10101010,석유와 가스 등 시추,유정 시추를 위해 서비스 계약을 체결한 시추 계약업자 또는 시추 장치 소유자. 태양...
1,10,에너지,WICS 대분류 (Major Sector),1010,에너지,WICS 중분류 (Medium Sector / Industry Group),101010,에너지장비및서비스,WICS 소분류 (Minor Sector / Industry),10101020,석유와 가스 등 에너지 장비 및 서비스,"시추 장치 및 장비를 제조하는 업체, 그리고 석유와 가스 유정의 시추, 평가, 생산..."
2,10,에너지,WICS 대분류 (Major Sector),1010,에너지,WICS 중분류 (Medium Sector / Industry Group),101020,석유와가스,WICS 소분류 (Minor Sector / Industry),10102010,종합 석유 및 가스,"석유와 가스의 탐사 및 생산과 관련된 종합 석유 회사로서, 이 외에 정유, 마케팅,..."
3,10,에너지,WICS 대분류 (Major Sector),1010,에너지,WICS 중분류 (Medium Sector / Industry Group),101020,석유와가스,WICS 소분류 (Minor Sector / Industry),10102020,석유와 가스 탐사 및 생산,다른 부문으로 분류되지 않은 석유와 가스의 탐사 및 생산 관련 기업
4,10,에너지,WICS 대분류 (Major Sector),1010,에너지,WICS 중분류 (Medium Sector / Industry Group),101020,석유와가스,WICS 소분류 (Minor Sector / Industry),10102030,석유와 가스 정제 및 마케팅,'종합 석유 및 가스' 또는 '독립 전력 생산업체 및 에너지 거래업체' 로 분류되지...

In [36]:
df.shape

(151, 12)

In [37]:
df.isnull().sum().sum()

np.int64(0)

In [38]:
df.to_csv('wics.csv', index=False, encoding='utf-8', header=True)